### ISSUE TITLE
Add backup support

### ISSUE THREAD

**Issue by tonybaloney** [DimensionDataCBUSydney/plumbery#16]
Add support for 
* Setting backup plan per node
* Adding agents
 * Configuring recipient and alerting option
 * Configuring storage and schedule policy
 * Choosing application
As well as having a 'polisher' that configures the CommVault agent via. SSH.

**Comment by tonybaloney** [comment]
It would be super-awesome if @jadunham1 would do this since he now has such a deep understanding of backup

**Comment by bernard357** [comment]
granted, this would be awesome - have you asked him to have a look at this?

**Comment by jadunham1** [comment]
I get pinged with his note, I can certainly take a look, just depends on how quickly you want this turned around.

**Comment by tonybaloney** [comment]
Oh hai Jeff! Fancy seeing you here... I'm going to start looking at this too, I don't want to lump it all on you.

**Comment by bernard357** [comment]
Just to ensure I understand the thing that is discussed here:

backup settings would be put in a list introduced by some keyword such as 'backup:', right?

backup:
- files: /mnt/to_be_backup
- slot: 6am
...

then plumbery would use the API to configure the backup job, and then connect via ssh to the Linux nodes to install the backup agent itself

Is this aligned with what you guys have in mind? This would be really an awesome automation capability :-)

**Comment by jadunham1** [comment]
Somewhat, but we don't really do file backups like that currently, it's pretty much all or nothing.
But yes, something like:
backup:
   plan: Enterprise
   client: FA.Linux
   storage: 14 Days
   schedule: 6AM - 12PM

And it would go in and enable the backups, add the client, and install the backup agent.

**Comment by bernard357** [comment]
ok, great -- my first guess would be to land this in polishers/configure.py (for the creation of the backup job) and in polishers/prepare.py (for access to the node in ssh and install the backup client). There is also a need to kill the backup job either in infrastructure.py or in nodes.py. This is according to the current architecture of course, yet it may evolve of course.

**Comment by tonybaloney** [comment]
I've just finished this @bernard357 @jadunham1 https://developer.dimensiondata.com/display/PLUM/Node+Objects#NodeObjects-backup

It's part of the 0.8.0 release
