### ISSUE TITLE
Docker file references branch version 0.8.0 does not exist

### ISSUE THREAD

**Issue by asimkhawaja** [DimensionDataCBUSydney/plumbery#21]
The latest docker file is referencing a branch version of 0.8.0 that does not exist!! . I think the tag just needs to be created or we need to update the Docker file to reference 0.7.0

The following message is received if I try to build the dockerfile:

Removing intermediate container 59d1e7ae5736
Step 14 : RUN git clone -b $VERSION --single-branch https://github.com/DimensionDataCBUSydney/plumbery
 ---> Running in cbe56dfe7aac
Cloning into 'plumbery'...
warning: Could not find remote branch 0.8.0 to clone.
fatal: Remote branch 0.8.0 not found in upstream origin

**Comment by bernard357** [comment]
You are correct. It seems that version has been moved internally to 0.8.0 after the addition of code to backup servers, however there are still a couple of steps to pass through to make it a real release.

**Comment by asimkhawaja** [comment]
this is now fixed
