### ISSUE TITLE
ok, plumbery 1.0 -- what is required to go there?

### ISSUE THREAD

**Issue by bernard357** [DimensionDataCBUSydney/plumbery#39]
[ ] restructure documentation as per wiki
[X] expand documentation to plumbery directives
[X] document connectivity options and the beachhead directive
[ ] reach 75% of test coverage
[X] change from xxx.parameter to parameter.xxx
[X] reach full compatibility with python3 -- Anthony
[ ] implement anti-affinity

**Comment by tonybaloney** [comment]
Python 3 support done

**Comment by bernard357** [comment]
change from xxx.parameter to parameter.xxx -- done

**Comment by bernard357** [comment]
massive documentation change on-going -- not finished yet, see my repo for details

**Comment by bernard357** [comment]
documentation of directives done, including beachhead

**Comment by bernard357** [comment]
little progress on documentation with 1.0.1

**Comment by bernard357** [comment]
closing this page as plumbery 1.0.2 has been released
