### ISSUE TITLE
Alternative way of installing ca-cert bundle

### ISSUE THREAD

**Issue by MartijnLohmeijer** [DimensionDataCBUSydney/plumbery#50]
When installing Plumbery through Windows install guide (https://github.com/DimensionDataCBUSydney/plumbery/blob/master/docs/installing.plumbery.windows.rst) I had some issues installing the bundle and kept getting certificate issues when trying to deploy new VM's. 

Through Google I found the pip certifi package (https://pypi.python.org/pypi/certifi / installs the Mozilla CA bundle) and after installing that I had no issues anymore. 

As plumbery itself is installed through pip anyway I thought this might be easier.

**Comment by bernard357** [comment]
Thanks @MartijnLohmeijer for this great feedback. The documentation will be adjusted accordingly. Are you ok to be listed as an additional project contributor?

**Comment by tonybaloney** [comment]
if you're using libcloud from trunk you don't even need to install any cert packages.
